---
title: "Cyclistic_EDA"
author: "Christopher Banner"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cyclistic Exploratory Data Analysis

```{r}
#package to handle this large csv file
options(repos = c(CRAN = "[https://cran.rstudio.com](https://cran.rstudio.com)")) # Explicitly set mirror here
#package to handle this large csv file

install.packages("data.table")
library(data.table)
```

```{r}
# reading in all the csv files for the previous 12 months of data

Divvy_24_Feb <- fread("202402-divvy-tripdata.csv")
Divvy_24_Mar <- fread("202403-divvy-tripdata.csv")
Divvy_24_Apr <- fread("202404-divvy-tripdata.csv")
Divvy_24_May <- fread("202405-divvy-tripdata.csv")
Divvy_24_Jun <- fread("202406-divvy-tripdata.csv")
Divvy_24_Jul <- fread("202407-divvy-tripdata.csv")
Divvy_24_Aug <- fread("202408-divvy-tripdata.csv")
Divvy_24_Sep <- fread("202409-divvy-tripdata.csv")
Divvy_24_Oct <- fread("202410-divvy-tripdata.csv")
Divvy_24_Nov <- fread("202411-divvy-tripdata.csv")
Divvy_24_Dec <- fread("202412-divvy-tripdata.csv")
Divvy_25_Jan <- fread("202501-divvy-tripdata.csv")
Divvy_25_Feb <- fread("202502-divvy-tripdata.csv")
```

```{r}
# efficient loop that verifies the colnames of each data.table without typing out each individual name.

months <- c("Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
years <- c(rep(24, 11), 25, 25) # 24 for Feb-Dec, 25 for Jan-Feb

for (i in 1:length(months)) {
  df_name <- paste0("Divvy_", years[i], "_", months[i])
  if (exists(df_name)) { # Check if the data frame exists
    print(colnames(get(df_name)))
  } else {
    print(paste("Data frame", df_name, "does not exist."))
  }
}
```

```{r}
# combining all the dataframes into one dataframe

Divvy_24_25 <- rbind(Divvy_24_Feb, Divvy_24_Mar, Divvy_24_Apr, Divvy_24_May, Divvy_24_Jun, Divvy_24_Jul, Divvy_24_Aug, Divvy_24_Sep, Divvy_24_Oct, Divvy_24_Nov, Divvy_24_Dec, Divvy_25_Jan, Divvy_25_Feb)

# inspecting the data

head(Divvy_24_25)
str(Divvy_24_25)
summary(Divvy_24_25)
missing_coords <- which(is.na(Divvy_24_25$end_lat))
summary(missing_coords)
```

```{r}
# Create a smaller subset (e.g., 10,000 rows)

subset_size <- 10000
subset_dt <- Divvy_24_25[1:subset_size]
```

```{r}
# This data.table is large, so i am using a subset join method for this process. I am looking to fix the NA values in the end_lat and end_lng columns. To do this, I am searching for the first non-NA value in the end_lat and end_lng columns for each end_station_name. This allows me to find the correct end_lat and end_lng values for the missing rows and complete the data.table. Running this as a loop would take far too much memory and computation time, this is why i went with the join method. 
# Measure start time

start_time <- Sys.time()

# Create valid coordinates data.table (using the full data.table)

valid_coords <- Divvy_24_25[!is.na(end_lat), .(end_lat = end_lat[1], end_lng = end_lng[1]), by = end_station_name]

# Update the main data.table using a join (using the full data.table)

Divvy_24_25[is.na(end_lat), `:=`(end_lat = valid_coords[.SD, end_lat, on = "end_station_name"],
                                 end_lng = valid_coords[.SD, end_lng, on = "end_station_name"])]

# Measure end time

end_time <- Sys.time()

# Calculate elapsed time

elapsed_time <- end_time - start_time

# Print elapsed time

print(paste("Elapsed time:", elapsed_time))

# Verify the changes

summary(Divvy_24_25)
```

```{r}
# Identify rows with missing end coordinates

missing_coords <- which(is.na(Divvy_24_25$end_lat))
summary(missing_coords)


# Check for missing values

missing_values <- colSums(is.na(Divvy_24_25))
print(missing_values)

# Check for duplicated rows

duplicated_rows <- sum(duplicated(Divvy_24_25))
print(duplicated_rows)

# Write to a new CSV file using fwrite to efficiently handle large data in the data.table

fwrite(Divvy_24_25, "Divvy_24_25.csv")

summary(Divvy_24_25)
tail(Divvy_24_25, 20)
```
